development:
  :address: smtp.gmail.com
  :port: 587
  :domain: gmail.com
  :enable_starttls_auto: true
  :authentication: :plain
  :user_name: <%= ENV["QFD_ACTION_MAILER_USER_NAME"] %>
  :password: <%= ENV["QFD_ACTION_MAILER_PASSWORD"] %>
