uservoice_options:
  # required
  key: <%= ENV["USERVOICE_USER"] %>
  host: qfdonline.uservoice.com
  forum: qfdonline
  # optional
  showTab: true
  alignment: left
  background_color: "#f00"
  text_color: white
  hover_color: "#06C"
  lang: en

uservoice_api:
  api_key: <%= ENV["USERVOICE_API_KEY"] %>